openapi: 3.1.0
info:
  title: Hello World Plugin
  description: A plugin for decorate the output of chatgpt.
  version: "v1"
servers:
  - url: http://localhost:3333
paths:
  /decorate:
    get:
      operationId: decorate
      summary: Query to get decoration. Decorate chatgpt output ending with [response]!
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/decorateResponse"
components:
  schemas:
    decorateResponse:
      type: string
      description: the decoration for ending
